name: Build/Deploy to mlb.rickysquid.org

on:
  push

jobs:
  install-priv-key-file-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: 'Production'
    steps:
      - uses: actions/checkout@v2
      - name: save key file from secret
        run: |
          echo {{ secret.SSH_PRIV_KEY }} > ./id_rickysquid
          pwd
          ls ~
          echo "ok"
          ls
          ssh -i ./id_rickysquid ubuntu@rickysquid.org 'bash -s' < ~/work/bball-react/bball-react/.github/scripts/grab-and-run-bball.sh