name: Build/Deploy to mlb.rickysquid.org

on:
  push

jobs:
  the-job:
    steps:
      - name: do it
        uses: actions/checkout@v2
        env:
          KEYF: ${{ secrets.SSH_PRIV_KEY }}
        run: |
          echo $KEYF
          echo $KEYF > ./id_rickysquid
          ssh -i ./id_rickysquid ubuntu@rickysquid.org 'bash -s' < ./scripts/grab-and-run-bball.sh