name: CI/CD Baby
on: push
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    environment: 'Production'
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat << EOF > ~/.ssh/config
          Host staging
            HostName ${{ secrets.SSH_DOMAIN_NAME }}
            User ${{ secrets.SSH_USER }}
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          EOF
          cat ~/.ssh/config
        # env:
        #   SSH_USER: ${{ secrets.SSH_USER }}
        #   SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        #   SSH_HOST: ${{ secrets.SSH_DOMAIN_NAME }}

      - name: deploy
        run: |
          cat << EOF > /tmp/hello.sh
          echo "heyo" > ~/heyo.txt
          EOF
          cat << EOF > /tmp/grab-and-run.sh
          cd /var/www/mlb.rickysquid.org/html/bball-react
          git pull
          npm install
          npm run build
          pgrep node
          pzid=$(pgrep node)
          echo "pzid is fucking empty its dumb as fuck"
          echo $pzid
          echo "see theres nothing in between"
          kill $pzid
          nohup node websocketd.js > bball-react.log 2>&1 &
          EOF
          cat ~/.ssh/staging.key
          ls -pal ~/.ssh
          ssh staging 'bash -s' < /tmp/grab-and-run.sh
