name: Build/Deploy to mlb.rickysquid.org

on:
  push

jobs:
  the-job:
    runs-on: ubuntu-latest
    steps:
      - name: do it
        env:
          KEYF: ${{ secrets.SSH_PRIVATE_KEY }}
          KH: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          ls
          echo $KH > ./known_hosts_ricky
          cat << EOF > /tmp/grab-and-run.sh
          cd /var/www/mlb.rickysquid.org/html/bball-react
          git pull
          npm run build
          npm run start &
          EOF
          echo $KEYF > ./id_rickysquid
          ssh -o UserKnownHostsFile=./known_hosts_ricky -i ./id_rickysquid ubuntu@rickysquid.org 'bash -s' < /tmp/grab-and-run.sh