name: Build/Deploy to Azure

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: ""

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .
  install-priv-key-file-and-deploy:
    steps:
      - name: save key file from secret
        run: |
          echo {{ secret.SSH_PRIV_KEY }} > ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa ubuntu@rickysquid.org bash ./.github/scripts/grab-and-run-bball.sh
  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'bball-react'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_F6D65FD6483F460088B60BD9EE3AEB92 }}
          package: .
