name: CI/CD
on: [push, pull_request]
jobs:
  # test:
  #   ...
  deploy:
    name: "Deploy to staging"
    runs-on: ubuntu-latest
    # needs: test
    steps:
      - name: Configure SSH
        run: |
          echo $SSH_USER
          echo $SSH_DOMAIN_NAME
          echo $SSH_DOMAIN
          echo ${{ secrets.SSH_USER }}
          mkdir -p ~/.ssh/
          echo "$SSH_KEY" > ~/.ssh/staging.key
          chmod 600 ~/.ssh/staging.key
          cat << EOF1 > ~/.ssh/config
          Host staging
            HostName $SSH_HOST
            User $SSH_USER
            IdentityFile ~/.ssh/staging.key
            StrictHostKeyChecking no
          EOF1
          cat ~/.ssh/config
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_DOMAIN_NAME }}

      - name: deploy
        run: |
          cat << EOF2 > /tmp/grab-and-run.sh
          cd /var/www/mlb.rickysquid.org/html/bball-react
          git pull
          npm run build
          npm run start &
          EOF2
          ssh staging 'bash -s' < /tmp/grab-and-run.sh
