name: Build/Deploy to mlb.rickysquid.org

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install, build
        run: |
          npm install
          npm run build --if-present
        env:
          CI: ""

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: node-app
          path: .
  install-priv-key-file-and-deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
    steps:
      - name: save key file from secret
        run: |
          echo {{ secret.SSH_PRIV_KEY }} > ~/.ssh/id_rsa
          ssh -i ~/.ssh/id_rsa ubuntu@rickysquid.org bash ./.github/scripts/grab-and-run-bball.sh