name: Build/Deploy to mlb.rickysquid.org

on:
  push

jobs:
  the-job:
    runs-on: ubuntu-latest
    steps:
      - name: do it
        env:
          KEYF: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          ls
          echo $KEYF > ./id_rickysquid
          ssh -i ./id_rickysquid ubuntu@rickysquid.org 'bash -s' < ./scripts/grab-and-run-bball.sh